import type { PortfolioCategory, PortfolioItem, VideoItem } from './types'

/**
 * Phase-2 local catalog — placeholder metadata while real photography is
 * remote-hosted later. The repository layer exposes these as `PortfolioItem`
 * records; the UI never imports this array directly.
 */

export const LOCAL_PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: 'p1',
    title: 'Monochrome — Frame 01',
    caption: 'Negative space studies',
    category: 'portraits',
    imageUrl: null,
    thumbnailUrl: null,
    year: '2026',
    description: 'A study in negative space — the subject yielded to the frame.',
    sortOrder: 1,
    published: true,
    featured: true,
    variant: '01',
  },
  {
    id: 'p2',
    title: 'Monochrome — Frame 02',
    caption: 'Architecture in shadow',
    category: 'events',
    imageUrl: null,
    thumbnailUrl: null,
    year: '2026',
    description: 'Lines and light on a building at dusk.',
    sortOrder: 2,
    published: true,
    featured: false,
    variant: '02',
  },
  {
    id: 'p3',
    title: 'Monochrome — Frame 03',
    caption: 'Portrait in low key',
    category: 'portraits',
    imageUrl: null,
    thumbnailUrl: null,
    year: '2025',
    description: 'Skin, shadow and a single hard source.',
    sortOrder: 3,
    published: true,
    featured: true,
    variant: '03',
  },
  {
    id: 'p4',
    title: 'Monochrome — Frame 04',
    caption: 'Grain, light, silence',
    category: 'weddings',
    imageUrl: null,
    thumbnailUrl: null,
    year: '2025',
    description: 'A quiet moment from the ceremony floor.',
    sortOrder: 4,
    published: true,
    featured: false,
    variant: '04',
  },
  {
    id: 'p5',
    title: 'Monochrome — Frame 05',
    caption: 'City after dusk',
    category: 'events',
    imageUrl: null,
    thumbnailUrl: null,
    year: '2025',
    description: 'The city settles into blue-hour silence.',
    sortOrder: 5,
    published: true,
    featured: false,
    variant: '05',
  },
  {
    id: 'p6',
    title: 'Monochrome — Frame 06',
    caption: 'Still life, hard light',
    category: 'birthdays',
    imageUrl: null,
    thumbnailUrl: null,
    year: '2024',
    description: 'Objects composed with a single window of light.',
    sortOrder: 6,
    published: true,
    featured: false,
    variant: '06',
  },
  {
    id: 'p7',
    title: 'Monochrome — Frame 07',
    caption: 'Skin and texture',
    category: 'portraits',
    imageUrl: null,
    thumbnailUrl: null,
    year: '2024',
    description: 'Close study of surface and tone.',
    sortOrder: 7,
    published: true,
    featured: true,
    variant: '07',
  },
  {
    id: 'p8',
    title: 'Monochrome — Frame 08',
    caption: 'Horizon studies',
    category: 'weddings',
    imageUrl: null,
    thumbnailUrl: null,
    year: '2024',
    description: 'Couples and coastlines at golden hour.',
    sortOrder: 8,
    published: true,
    featured: false,
    variant: '08',
  },
]

export const LOCAL_PORTFOLIO_CATEGORIES: PortfolioCategory[] = [
  { id: 'weddings', name: 'WEDDINGS', slug: 'weddings', description: 'Ceremony and celebration.', sortOrder: 1, published: true },
  { id: 'events', name: 'EVENTS', slug: 'events', description: 'Live moments, captured.', sortOrder: 2, published: true },
  { id: 'birthdays', name: 'BIRTHDAYS', slug: 'birthdays', description: 'Days worth keeping.', sortOrder: 3, published: true },
  { id: 'portraits', name: 'PORTRAITS', slug: 'portraits', description: 'The study of a face.', sortOrder: 4, published: true },
]

export const LOCAL_VIDEOS: VideoItem[] = []
